# Generated by Django 3.1.2 on 2022-09-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220915_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='relations',
        ),
        migrations.RemoveField(
            model_name='object',
            name='article',
        ),
        migrations.AddField(
            model_name='object',
            name='article',
            field=models.ManyToManyField(related_name='scope', to='articles.Article'),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
